source 'https://rubygems.org'
 
gem 'berkshelf'
gem 'test-kitchen', :git => 'https://github.com/zl4bv/test-kitchen', :branch => 'windows_support'
gem 'kitchen-ec2', :git => 'https://github.com/zl4bv/kitchen-ec2', :branch => 'windows_support'
gem 'winrm-transport'

