source 'https://rubygems.org'

gem 'rake'
gem 'berkshelf'
gem 'chefspec'

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'winrm-transport'
  gem 'vagrant-winrm'

  # WinRM Transport requires the vagrant-winrm Vagrant plugin to properly
  # communicate with this Vagrant VM.
  # Please install this plugin with: `vagrant plugin install vagrant-winrm'
  # and try again.
end