source 'https://rubygems.org'

gem 'rake'

gem 'aws-sdk', '2.1.7'
gem 'puppet_forge', '<= 1.0.2'
gem 'test-kitchen'
gem 'kitchen-puppet'
gem 'kitchen-docker'
gem 'kitchen-transport-sshtar'
gem 'kitchen-vagrant'
gem 'kitchen-ec2', '0.10.0'
gem 'vagrant-wrapper'
